Prevent interpreting this placeholder as a JSX/HTML tag (#1257)
When I tried to upgrade Docusaurus to 3.5 locally it refused to process
this code with

    [ERROR] Client bundle compiled with errors therefore further build is impossible.
    Error: MDX compilation failed for file "/lune/lune-docs/docs/guides/lune-pay.md"
    Cause: Expected a closing tag for `<redirect_label>` (105:85-105:101) before the end of `paragraph`
    Details:
    {
      "column": 3,
      "message": "Expected a closing tag for `<redirect_label>` (105:85-105:101) before the end of `paragraph`",
      "line": 105,
      "name": "105:3-105:109",
      "place": {
        "start": {
          "line": 105,
          "column": 3,
          "offset": 2371,
          "_index": 0,
          "_bufferIndex": 0
        },
        "end": {
          "line": 105,
          "column": 109,
          "offset": 2477,
          "_index": 1,
          "_bufferIndex": -1
        }
      },
      "reason": "Expected a closing tag for `<redirect_label>` (105:85-105:101) before the end of `paragraph`",
      "ruleId": "end-tag-mismatch",
      "source": "mdast-util-mdx-jsx"
    }

and I believe it makes sense to escape these angle brackets anyway, even
without upgrading anything, just to avoid ambiguity.