Revert "Bump react and @types/react (#1116)" (#1123)
It appears that the documentation application isn't quite ready for
React 18 at the moment, at the very least the sidebar is broken and the
browser console is filled with instances of

    TypeError: L.current.useInsertionEffect is not a function
        useInsertionEffect https://docs.lune.co/assets/js/main.770731a1.js:1
        dn https://docs.lune.co/assets/js/common.1e2920f2.js:2
        si https://docs.lune.co/assets/js/main.770731a1.js:1
        Ws https://docs.lune.co/assets/js/main.770731a1.js:1
        Nl https://docs.lune.co/assets/js/main.770731a1.js:1
        Tl https://docs.lune.co/assets/js/main.770731a1.js:1
        Cl https://docs.lune.co/assets/js/main.770731a1.js:1
        vl https://docs.lune.co/assets/js/main.770731a1.js:1
        fl https://docs.lune.co/assets/js/main.770731a1.js:1
        ec https://docs.lune.co/assets/js/main.770731a1.js:1
        ic https://docs.lune.co/assets/js/main.770731a1.js:1
        kl https://docs.lune.co/assets/js/main.770731a1.js:1
        ic https://docs.lune.co/assets/js/main.770731a1.js:1
        hydrate https://docs.lune.co/assets/js/main.770731a1.js:1
        97221 https://docs.lune.co/assets/js/main.770731a1.js:1
        promise callback*97221 https://docs.lune.co/assets/js/main.770731a1.js:1
        t https://docs.lune.co/assets/js/runtime~main.9bfc762d.js:1
        <anonymous> https://docs.lune.co/assets/js/main.770731a1.js:1
        O https://docs.lune.co/assets/js/runtime~main.9bfc762d.js:1
        <anonymous> https://docs.lune.co/assets/js/main.770731a1.js:1
        a https://docs.lune.co/assets/js/runtime~main.9bfc762d.js:1
        <anonymous> https://docs.lune.co/assets/js/main.770731a1.js:1
    main.770731a1.js:1:410349
        us https://docs.lune.co/assets/js/main.770731a1.js:1
        callback https://docs.lune.co/assets/js/main.770731a1.js:1
        ho https://docs.lune.co/assets/js/main.770731a1.js:1
        bs https://docs.lune.co/assets/js/main.770731a1.js:1
        Ol https://docs.lune.co/assets/js/main.770731a1.js:1
        unstable_runWithPriority https://docs.lune.co/assets/js/main.770731a1.js:1
        Za https://docs.lune.co/assets/js/main.770731a1.js:1
        Ll https://docs.lune.co/assets/js/main.770731a1.js:1
        vl https://docs.lune.co/assets/js/main.770731a1.js:1
        fl https://docs.lune.co/assets/js/main.770731a1.js:1
        ec https://docs.lune.co/assets/js/main.770731a1.js:1
        ic https://docs.lune.co/assets/js/main.770731a1.js:1
        kl https://docs.lune.co/assets/js/main.770731a1.js:1
        ic https://docs.lune.co/assets/js/main.770731a1.js:1
        hydrate https://docs.lune.co/assets/js/main.770731a1.js:1
        97221 https://docs.lune.co/assets/js/main.770731a1.js:1
        (Async: promise callback)
        97221 https://docs.lune.co/assets/js/main.770731a1.js:1
        t https://docs.lune.co/assets/js/runtime~main.9bfc762d.js:1
        <anonymous> https://docs.lune.co/assets/js/main.770731a1.js:1
        O https://docs.lune.co/assets/js/runtime~main.9bfc762d.js:1
        <anonymous> https://docs.lune.co/assets/js/main.770731a1.js:1
        a https://docs.lune.co/assets/js/runtime~main.9bfc762d.js:1
        <anonymous> https://docs.lune.co/assets/js/main.770731a1.js:1

We'll likely want to upgrade to React 18, we just need some time to look
at this more closely.

This reverts commit a4225d0a4a342a36618e14fe644a7dbe6451d9f4.